using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Sander.AssemblyRebinding;

namespace AssemblyRebindingTests
{
	[TestClass]
	public class ParsingTests
	{
		private readonly List<string> _lines = new List<string>
		{
			"1>  Consider app.config remapping of assembly \"System.Diagnostics.Tracing, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.20.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Diagnostics.Tracing.dll] to Version \"4.2.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Diagnostics.Tracing.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Dynamic.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Dynamic.Runtime.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Dynamic.Runtime.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Globalization, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Globalization.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Globalization.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Globalization.Extensions, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"0.0.0.0\" [] to Version \"4.1.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Globalization.Extensions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.IO.Compression, Culture=neutral, PublicKeyToken=b77a5c561934e089\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\System.IO.Compression.dll] to Version \"4.2.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.IO.Compression.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.IO.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.IO.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Linq, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Linq.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Linq.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Linq.Expressions, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Linq.Expressions.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Linq.Expressions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Linq.Parallel, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Linq.Parallel.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Linq.Parallel.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Linq.Queryable, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Linq.Queryable.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Linq.Queryable.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Net.NetworkInformation, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Net.NetworkInformation.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Net.NetworkInformation.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Net.Primitives.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Net.Primitives.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Net.Requests, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Net.Requests.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Net.Requests.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Net.Sockets, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"0.0.0.0\" [] to Version \"4.2.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Net.Sockets.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.ObjectModel, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.ObjectModel.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.ObjectModel.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Reflection, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Reflection.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Reflection.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Reflection.Extensions, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Reflection.Extensions.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Reflection.Extensions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Reflection.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Reflection.Primitives.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Reflection.Primitives.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Resources.ResourceManager, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Resources.ResourceManager.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Resources.ResourceManager.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Runtime.Extensions, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Runtime.Extensions.dll] to Version \"4.1.2.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Runtime.Extensions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Runtime.Numerics, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Runtime.Numerics.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Runtime.Numerics.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Runtime.Serialization.Json, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Runtime.Serialization.Json.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Runtime.Serialization.Json.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Runtime.Serialization.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Runtime.Serialization.Primitives.dll] to Version \"4.2.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Runtime.Serialization.Primitives.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Runtime.Serialization.Xml, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Runtime.Serialization.Xml.dll] to Version \"4.1.3.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Runtime.Serialization.Xml.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Security.Cryptography.Algorithms, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"0.0.0.0\" [] to Version \"4.3.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Security.Cryptography.Algorithms.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Security.Principal, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Security.Principal.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Security.Principal.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Security.SecureString, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"0.0.0.0\" [] to Version \"4.1.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Security.SecureString.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Text.Encoding, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Text.Encoding.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Text.Encoding.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Text.Encoding.Extensions, Culture=neutral, PublicKeyToken=null\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Text.Encoding.Extensions.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Text.Encoding.Extensions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Text.RegularExpressions, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Text.RegularExpressions.dll] to Version \"4.1.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Text.RegularExpressions.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Threading, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Threading.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Threading.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Threading.Overlapped, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"0.0.0.0\" [] to Version \"4.1.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Threading.Overlapped.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Threading.Tasks.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Threading.Tasks.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Threading.Tasks.Parallel, Culture=neutral, PublicKeyToken=null\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Threading.Tasks.Parallel.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Threading.Tasks.Parallel.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Threading.Timer, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.0.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Threading.Timer.dll] to Version \"4.0.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Threading.Timer.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Xml.ReaderWriter, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Xml.ReaderWriter.dll] to Version \"4.1.1.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Xml.ReaderWriter.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Xml.XDocument, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Xml.XDocument.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Xml.XDocument.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Xml.XmlSerializer, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" from Version \"4.0.10.0\" [C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\Facades\\System.Xml.XmlSerializer.dll] to Version \"4.0.11.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Xml.XmlSerializer.dll] to solve conflict and get rid of warning.",
"1>  Consider app.config remapping of assembly \"System.Xml.XPath.XDocument, Culture=neutral, PublicKeyToken=null\" from Version \"0.0.0.0\" [] to Version \"4.1.0.0\" [C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\Microsoft\\Microsoft.NET.Build.Extensions\\net461\\lib\\System.Xml.XPath.XDocument.dll] to solve conflict and get rid of warning."
		};


		[TestMethod]
		public void Parse()
		{
			var result = Rebinder.Run(_lines, Logger);
			PrintList(result);
			Assert.AreEqual(_lines.Count, result.Count);
		}


		[TestMethod]
		public void ParseWithBadLine()
		{
			var lines = _lines.ToList();
			lines.Add("This line will fail parsing!");
			var result = Rebinder.Run(lines, Logger);
			PrintList(result);
			Assert.AreNotEqual(lines.Count, result.Count);
		}

		private static void PrintList(List<string> result)
		{
			foreach (var line in result)
			{
				Trace.WriteLine(line);
			}
		}

		private void Logger(LogLevel x, string y) => Trace.WriteLine($"[{x}] {y}");
	}
}
